spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings : false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

secret:
  access: acc
  refresh: ref