spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings : false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

secret:
  access: acc
  refresh: ref