spring:
  jpa:
    hibernate:
      ddl-auto: update
<<<<<<< HEAD
      use-new-id-generator-mappings : false
=======
>>>>>>> develop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
secret:
  access: acc
  refresh: ref